//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class commentUser
    {
        public int id { get; set; }
        public System.DateTime datecomment { get; set; }
        public string commentUser1 { get; set; }
        public int user_id { get; set; }
        public int task_id { get; set; }
    
        public virtual task task { get; set; }
        public virtual userlist userlist { get; set; }
    }
}
