//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskPro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TPEntities : DbContext
    {
        public TPEntities()
            : base("name=TPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attachment> attachment { get; set; }
        public virtual DbSet<commentUser> commentUser { get; set; }
        public virtual DbSet<list> list { get; set; }
        public virtual DbSet<listacess> listacess { get; set; }
        public virtual DbSet<memberlist> memberlist { get; set; }
        public virtual DbSet<tag> tag { get; set; }
        public virtual DbSet<task> task { get; set; }
        public virtual DbSet<tasktag> tasktag { get; set; }
        public virtual DbSet<timetrack> timetrack { get; set; }
        public virtual DbSet<userlist> userlist { get; set; }
    }
}
