//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskPro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TPEntities : DbContext
    {
        public TPEntities()
            : base("name=TPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attachment> attachments { get; set; }
        public virtual DbSet<commentUser> commentUsers { get; set; }
        public virtual DbSet<list> lists { get; set; }
        public virtual DbSet<listacess> listacesses { get; set; }
        public virtual DbSet<tag> tags { get; set; }
        public virtual DbSet<task> tasks { get; set; }
        public virtual DbSet<tasktag> tasktags { get; set; }
        public virtual DbSet<timetrack> timetracks { get; set; }
        public virtual DbSet<userlist> userlists { get; set; }
    }
}
